"""T147 — no input reaches an unhandled exception, and every refusal carries exactly one code.

Totality is the property the whole inbound boundary rests on. A listener, a simulator or the CLI
hands `convert` whatever arrived, and "whatever arrived" includes bytes nobody intended: truncated
JSON, a number where a string belongs, a field nobody declared, an object that is not the canonical
request at all.

Two statements, and they are different:

* **total** — the function returns. Not "raises a documented exception", not "raises a violation
  which a caller is expected to catch": returns a value of the declared union.
* **one code** — a refusal names exactly one reason code, so a caller reporting it cannot choose. A
  refusal with two codes is two refusals wearing one; a refusal with none is a shrug.

## Why generated bytes rather than a corpus of bad payloads

A corpus of malformed inputs tests what its author thought of. `convert` parses, verifies a
signature, checks a message kind, applies bounds, normalises text and resolves identity — six places
where a value of an unexpected shape could reach an operation that assumes otherwise. The
generator's job is to reach the ones nobody listed.

The signature is **not** generated valid here. Most generated bodies fail verification, which is the
correct behaviour and also means this file mostly exercises the early steps; the deeper steps are
reached by the valid-signature strategy that signs whatever body it generated.
"""

from __future__ import annotations

import json

import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from channel_integration.contracts.descriptor import ChannelId
from channel_integration.contracts.envelope import ChannelEnvelope
from channel_integration.contracts.kinds import MessageKind
from channel_integration.contracts.raw import RawChannelRequest
from channel_integration.contracts.reason_codes import ChannelReasonCode
from channel_integration.contracts.refusal import ChannelRefusal
from channel_integration.inbound.convert import convert

from ..fixtures.channels import (
    AT,
    FIXTURE_MATERIAL,
    bounds_for,
    descriptor_for,
    signed_request,
    wire_payload,
)
from ..fixtures.identity import (
    FIXTURE_EXTERNAL,
    CountingIdentityResolver,
    CountingPseudonymiser,
    active_binding,
)

pytestmark = pytest.mark.property

_CHANNELS = tuple(ChannelId)

_SCALARS = st.one_of(
    st.none(),
    st.booleans(),
    st.integers(),
    st.floats(allow_nan=False, allow_infinity=False),
    st.text(max_size=40),
)

#: A wire payload with generated field values and, sometimes, undeclared fields. Undeclared fields
#: matter: `004` refuses them rather than ignoring them, and that refusal must be a refusal and not
#: a validation error escaping through the return type.
_PAYLOADS = st.dictionaries(
    keys=st.one_of(
        st.sampled_from(
            ("tenant", "language", "reference_date", "message_id", "text", "attachment", "caption")
        ),
        st.text(min_size=1, max_size=12),
    ),
    values=_SCALARS,
    max_size=8,
)


def _run(raw: object, channel: ChannelId, kind: MessageKind) -> ChannelEnvelope | ChannelRefusal:
    return convert(
        raw,
        descriptor=descriptor_for(channel),
        material=FIXTURE_MATERIAL,
        bounds=bounds_for(channel),
        kind=kind,
        external=FIXTURE_EXTERNAL,
        resolver=CountingIdentityResolver(active_binding(channel=channel)),
        pseudonymiser=CountingPseudonymiser(),
        at=AT,
    )


def _is_total(outcome: object) -> bool:
    return isinstance(outcome, ChannelEnvelope | ChannelRefusal)


@settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(
    payload=_PAYLOADS,
    channel=st.sampled_from(_CHANNELS),
    kind=st.sampled_from(tuple(MessageKind)),
)
def test_a_generated_payload_always_returns_an_outcome(
    payload: dict[str, object],
    channel: ChannelId,
    kind: MessageKind,
) -> None:
    """Signed correctly, so the generated values reach the steps past verification."""
    raw = signed_request(channel, body=json.dumps(payload).encode())
    outcome = _run(raw, channel, kind)
    assert _is_total(outcome), f"convert returned {type(outcome).__name__}"


@settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(body=st.binary(max_size=200), channel=st.sampled_from(_CHANNELS))
def test_arbitrary_bytes_always_return_an_outcome(body: bytes, channel: ChannelId) -> None:
    """Bytes that are not JSON, not UTF-8, or empty. The listener cannot promise otherwise."""
    raw = RawChannelRequest(
        channel=channel,
        body=body,
        headers=(("content-type", "application/json"),),
        received_at=AT,
    )
    outcome = _run(raw, channel, MessageKind.TEXT)
    assert _is_total(outcome)


@settings(max_examples=80, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(alien=_SCALARS)
def test_an_object_that_is_not_the_canonical_request_refuses_rather_than_raising(
    alien: object,
) -> None:
    """A caller handing over the wrong type is malformed input, not a programming error.

    Asserted because the alternative is attractive and wrong: raising `TypeError` here would be
    defensible in a library with a checked caller, and this boundary has no checked caller.
    """
    outcome = _run(alien, ChannelId.SLACK, MessageKind.TEXT)
    assert isinstance(outcome, ChannelRefusal)
    assert outcome.code is ChannelReasonCode.CHANNEL_PAYLOAD_MALFORMED


@settings(max_examples=200, deadline=None, suppress_health_check=[HealthCheck.too_slow])
@given(
    payload=_PAYLOADS,
    channel=st.sampled_from(_CHANNELS),
    kind=st.sampled_from(tuple(MessageKind)),
)
def test_every_refusal_carries_exactly_one_code_from_this_features_namespace(
    payload: dict[str, object],
    channel: ChannelId,
    kind: MessageKind,
) -> None:
    """One code, and it is `004`'s.

    The namespace half matters as much as the count: a refusal carrying an upstream code would make
    this feature's boundary indistinguishable from a failure inside `001`, `002` or `003`, and the
    four disjoint namespaces exist so a reader can tell which layer refused.
    """
    raw = signed_request(channel, body=json.dumps(payload).encode())
    outcome = _run(raw, channel, kind)
    if isinstance(outcome, ChannelEnvelope):
        return
    assert isinstance(outcome.code, ChannelReasonCode)
    assert outcome.code.value in {member.value for member in ChannelReasonCode}


def test_the_generated_inputs_reach_both_outcomes() -> None:
    """Anti-vacuity: the strategies above produce envelopes **and** refusals.

    Without this, a generator that only ever produced malformed bytes would satisfy every property
    here while proving nothing about the successful path — and the properties would still be green.
    """
    channel = ChannelId.SLACK
    envelope = _run(signed_request(channel, payload=wire_payload()), channel, MessageKind.TEXT)
    refused = _run(
        signed_request(channel, body=b"{not json"),
        channel,
        MessageKind.TEXT,
    )
    assert isinstance(envelope, ChannelEnvelope), "the fixture payload no longer converts"
    assert isinstance(refused, ChannelRefusal), "malformed bytes no longer refuse"
