"""Structure → text — T052 (FR-002; SC-001).

``render`` walks a ``QueryStructure`` and emits ``RenderedQuery{text, parameters}``.
It accepts **nothing else**: no string, no fragment, no options object with an
escape hatch. There is no overload and no ``render_raw`` variant, so the only way
to produce query text in this package is to build a typed tree first.

Every caller value leaves through ``parameters``. The text contains governed
identifiers, SQL keywords, and ``@placeholder`` names generated by the compiler —
and the emitted-text guard asserts afterwards that no parameter *value* appears
in it, which catches a future refactor that reintroduces interpolation even if
this function still looks correct.

Output is deterministic: slots are emitted in structure order and the structure
is built in request order after normalisation, so the same governed request
renders byte-identical text every time (`SC-014` is about identity; this is the
narrower property that identity depends on).
"""

from __future__ import annotations

from datetime import date
from typing import TYPE_CHECKING

from semantic_catalog.contracts.metric import Aggregation

from ..contracts.operators import GovernedOperator
from ..execution.adapter import RenderedQuery, ScalarValue
from .slots import CompilationDefect

if TYPE_CHECKING:  # pragma: no cover - typing only
    from .plan import PredicateSlot, ProjectionSlot, QueryStructure

__all__ = ["render"]

#: How each governed aggregation becomes SQL. A closed mapping: an aggregation
#: `001` adds later fails here loudly rather than rendering as something plausible.
_AGGREGATION_SQL: dict[Aggregation, str] = {
    Aggregation.SUM: "SUM",
    Aggregation.COUNT_DISTINCT: "COUNT(DISTINCT {column})",
    Aggregation.SNAPSHOT_LAST: "ANY_VALUE",
}

#: How each governed operator becomes a predicate. Closed for the same reason.
_OPERATOR_SQL: dict[GovernedOperator, str] = {
    GovernedOperator.EQ: "{column} = {p0}",
    GovernedOperator.NE: "{column} <> {p0}",
    GovernedOperator.IN: "{column} IN ({plist})",
    GovernedOperator.NOT_IN: "{column} NOT IN ({plist})",
    GovernedOperator.BETWEEN: "{column} BETWEEN {p0} AND {p1}",
}


def render(structure: QueryStructure) -> RenderedQuery:
    """Emit text and bound parameters from a typed structure.

    Takes a ``QueryStructure`` and nothing else — deliberately. A second
    parameter accepting a fragment, a hint or an override would be the seam
    through which caller text eventually reaches the warehouse.
    """
    select_terms = [_projection(p) for p in structure.projections]
    select_terms = [
        f"{_group_column(g.column)} AS {g.dimension_id}" for g in structure.group_by
    ] + select_terms

    where_terms: list[str] = []
    if structure.date_start is not None and structure.date_end is not None:
        start, end = structure.date_start.name, structure.date_end.name
        where_terms.append(f"{structure.date_column} BETWEEN @{start} AND @{end}")
    where_terms.extend(_predicate(p) for p in structure.predicates)

    text = f"SELECT {', '.join(select_terms)} FROM `{structure.table.view}`"
    if where_terms:
        text += " WHERE " + " AND ".join(where_terms)
    if structure.group_by:
        text += " GROUP BY " + ", ".join(g.dimension_id for g in structure.group_by)

    parameters: dict[str, ScalarValue] = {
        name: _scalar(value) for name, value in structure.parameters().items()
    }
    return RenderedQuery(text=text, parameters=parameters)


def _projection(slot: ProjectionSlot) -> str:
    template = _AGGREGATION_SQL.get(slot.aggregation)
    if template is None:
        # `ratio` has a numerator and denominator the catalog states in prose; it
        # has no single governed column to aggregate, so rendering one would be
        # inventing the calculation rather than reading it.
        raise CompilationDefect(f"aggregation {slot.aggregation.value!r} has no governed rendering")
    body = (
        template.format(column=slot.column)
        if "{column}" in template
        else f"{template}({slot.column})"
    )
    return f"{body} AS {slot.alias}"


def _group_column(column: str) -> str:
    return column


def _predicate(slot: PredicateSlot) -> str:
    names = [f"@{p.name}" for p in slot.parameters]
    template = _OPERATOR_SQL[slot.operator]
    return template.format(
        column=slot.column,
        p0=names[0] if names else "",
        p1=names[1] if len(names) > 1 else "",
        plist=", ".join(names),
    )


def _scalar(value: str | int | float | bool | date) -> ScalarValue:
    """Dates travel as ISO strings; everything else is already scalar.

    Conversion happens here rather than in the structure so the structure keeps
    the caller's own type, which is what the injection tests inspect.
    """
    return value.isoformat() if isinstance(value, date) else value
